apiVersion: v1
kind: Service
metadata:
  name: telco-nf-service
spec:
  type: NodePort              # Expose outside cluster
  selector:
    app: telco-nf             # Send traffic to these pods
  ports:
  - port: 80                  # Service port
    targetPort: 5000          # Container port
